version: '3.8'

services:
  workspace:
    build:
      context: ./docker
      dockerfile: Dockerfile.node-dev
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "6006:6006"
    networks:
      - memoria-network
    tty: true
    command: /bin/bash

networks:
  memoria-network:
    external: true
