version: '3.8'

services:
  memoria-api:
    build:
      context: ./docker
      dockerfile: Dockerfile.go-dev
    volumes:
      - .:/backend
    working_dir: /backend/services/memoria-api
    ports:
      - "4200:4200"
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        make run
