// Code generated by MockGen. DO NOT EDIT.
// Source: domain/interfaces/bgjob.go
//
// Generated by this command:
//
//	mockgen -source=domain/interfaces/bgjob.go -destination=testutil/mock/bgjob.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	interfaces "memoria-api/domain/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBGJob is a mock of BGJob interface.
type MockBGJob struct {
	ctrl     *gomock.Controller
	recorder *MockBGJobMockRecorder
}

// MockBGJobMockRecorder is the mock recorder for MockBGJob.
type MockBGJobMockRecorder struct {
	mock *MockBGJob
}

// NewMockBGJob creates a new mock instance.
func NewMockBGJob(ctrl *gomock.Controller) *MockBGJob {
	mock := &MockBGJob{ctrl: ctrl}
	mock.recorder = &MockBGJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBGJob) EXPECT() *MockBGJobMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockBGJob) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockBGJobMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockBGJob)(nil).Start))
}

// MockBGJobInvoker is a mock of BGJobInvoker interface.
type MockBGJobInvoker struct {
	ctrl     *gomock.Controller
	recorder *MockBGJobInvokerMockRecorder
}

// MockBGJobInvokerMockRecorder is the mock recorder for MockBGJobInvoker.
type MockBGJobInvokerMockRecorder struct {
	mock *MockBGJobInvoker
}

// NewMockBGJobInvoker creates a new mock instance.
func NewMockBGJobInvoker(ctrl *gomock.Controller) *MockBGJobInvoker {
	mock := &MockBGJobInvoker{ctrl: ctrl}
	mock.recorder = &MockBGJobInvokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBGJobInvoker) EXPECT() *MockBGJobInvokerMockRecorder {
	return m.recorder
}

// CreateThumbnails mocks base method.
func (m *MockBGJobInvoker) CreateThumbnails(dto interfaces.BGJobInvokerCreateThumbnailsDTO) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateThumbnails", dto)
}

// CreateThumbnails indicates an expected call of CreateThumbnails.
func (mr *MockBGJobInvokerMockRecorder) CreateThumbnails(dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThumbnails", reflect.TypeOf((*MockBGJobInvoker)(nil).CreateThumbnails), dto)
}
