FROM golang:1.22.2-bookworm

RUN go install github.com/go-delve/delve/cmd/dlv@v1.22.1 \
  && go install github.com/cespare/reflex@v0.3.1 \
  && go install github.com/vektra/mockery/v3@v3.0.0-alpha.0 \
  && go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.17.1

CMD ["/bin/bash"]
